#' Initialize a shidashi application
#'
#' @description
#' Creates a fresh environment holding all per-application state
#' (session registry, per-module input registries, etc.) and assigns it
#' to \code{.__shidashi_globals__.} in the caller's environment.
#' This function is designed to be called from a \file{global.R} file
#' generated by \code{\link{render}()}, where the caller's environment is
#' the global environment.
#'
#' @param env the environment in which to store the globals variable;
#'   defaults to the caller's environment.
#'
#' @return The globals environment (invisibly).
#'
#' @details
#' The assigned variable \code{.__shidashi_globals__.} is an environment
#' (with parent \code{emptyenv()}) containing:
#' \describe{
#'   \item{\code{mcp_session_registry}}{A \code{fastmap::fastmap()} keyed by
#'     Shiny session token, storing MCP session entries.}
#'   \item{\code{module_input_registry}}{A \code{fastmap::fastmap()} keyed by
#'     module ID.
#'     Each value is itself a \code{fastmap} storing input specifications
#'     registered via \code{\link{register_input}()}.}
#'   \item{\code{get_module_input_specs(module_id)}}{A convenience function
#'     that returns the per-module input \code{fastmap}, creating it on first
#'     access.}
#' }
#'
#' Internal package functions obtain this environment via
#' \code{get_shidashi_globals()}, which walks the caller chain with
#' \code{inherits = TRUE}.
#'
#' @examples
#' # Typically called from global.R (generated by render()):
#' #   shidashi::init_app()
#'
#' # Manual usage for testing:
#' env <- new.env()
#' shidashi::init_app(env = env)
#' ls(env$.__shidashi_globals__.)
#'
#' @export
init_app <- function(env = parent.frame()) {

  global_env <- new.env(parent = emptyenv())

  global_env$mcp_session_registry <- fastmap::fastmap()

  global_env$module_input_registry <- fastmap::fastmap()

  global_env$get_module_input_specs <- function(module_id) {
    if (!global_env$module_input_registry$has(module_id)) {
      global_env$module_input_registry$set(module_id, fastmap::fastmap())
    }
    global_env$module_input_registry$get(module_id)
  }

  env$.__shidashi_globals__. <- global_env

  invisible(global_env)
}


#' Retrieve the shidashi globals environment
#'
#' @description
#' Looks up \code{.__shidashi_globals__.} by walking the environment chain
#' from \code{env} upward.  Because \file{global.R} assigns the variable
#' into the global environment, any code running in a child environment
#' (UI rendering, server functions, module code) will find it via
#' \code{inherits = TRUE}.
#'
#' @param env starting environment for the lookup; defaults to the
#'   caller's environment.
#'
#' @return The globals environment created by \code{\link{init_app}()}.
#'   Raises an error if \code{.__shidashi_globals__.} cannot be found
#'   (i.e. \code{init_app()} was never called).
#'
#' @keywords internal
#' @export
get_shidashi_globals <- function(env = parent.frame()) {
  get(
    ".__shidashi_globals__.",
    envir = env,
    inherits = TRUE,
    mode = "environment"
  )
}
